name: "Build Dereferenced IDN V3"

on:
  push:
    branches:
      - main
    paths:
      - idn/sailpoint-api.v3.yaml
      - idn/v3/**
  workflow_dispatch:

jobs:
  dereference_spec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install swagger-cli and postman
        run: |
          npm install -g swagger-cli
          npm install -g openapi-to-postmanv2
      - name: Dereference API Specification and build Postman collection
        run: |
          swagger-cli bundle --dereference idn/sailpoint-api.v3.yaml -t yaml -o dereferenced/deref-sailpoint-api.v3.yaml
          openapi2postmanv2 -s dereferenced/deref-sailpoint-api.v3.yaml -o postman/collections/sailpoint-api-v3.json -p -O folderStrategy=Tags,requestParametersResolution=Schema,exampleParametersResolution=Schema,disableOptionalParameters=true,optimizeConversion=false,stackLimit=50,alwaysInheritAuthentication=true
          node postman-script/modify-collection.js postman/collections/sailpoint-api-v3.json

      - uses: stefanzweifel/git-auto-commit-action@v4
