name: "Push API Specs to Developer Portal"

on:
  push:
    branches:
      - main
    paths:
      - idn/sailpoint-api.v3.yaml
      - idn/v3/**

jobs:
  dereference_spec:
    name: Push API spec changes
    runs-on: ubuntu-latest
    steps:
      # Checkout the master branch request to run rsync
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          
      # Node is required for npm
      - name: Set up Node
        uses: actions/setup-node@v3

      - name: Install swagger-cli
        run: |
          npm install -g @apidevtools/swagger-cli

      - name: Dereference API Specification
        run: |
          swagger-cli bundle --dereference idn/sailpoint-api.v3.yaml -t yaml -o dereferenced/idn-v3-spec.yaml

      - uses: stefanzweifel/git-auto-commit-action@v4