name: "Build and push powershell sdk"

on:
  push:
    branches:
      - main
    paths:
      - idn/**
  workflow_dispatch:

jobs:
  push_powershell_sdk_workflow:
    name: Build and push Powershell SDK
    runs-on: ubuntu-latest
    steps:
      # Checkout the master branch request to run rsync
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      # Checkout the main branch of api-specs
      - name: Checkout API Specs Repo
        uses: actions/checkout@v2
        with:
          repository: sailpoint-oss/powershell-sdk
          path: powershell-sdk
          ref: main

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Build V3 SDK
        id: buildV3
        run: |
          cd powershell-sdk
          rm -rf ./sdk-output/v3
          java -jar openapi-generator-cli.jar generate -i ../idn/sailpoint-api.v3.yaml -g powershell -o sdk-output/v3 --global-property skipFormModel=false --config sdk-resources/v3-config.yaml
          node sdk-resources/postscript.js ./sdk-output/v3

      - name: Build Beta SDK
        id: buildBeta
        if: steps.buildV3.outcome == 'success'
        run: |
          cd powershell-sdk
          rm -rf ./sdk-output/beta
          java -jar openapi-generator-cli.jar generate -i ../idn/sailpoint-api.beta.yaml -g powershell -o sdk-output/beta --global-property skipFormModel=false --config sdk-resources/beta-config.yaml

      - name: Build V2 SDK
        id: buildV2
        if: steps.buildBeta.outcome == 'success'
        run: |
          cd powershell-sdk
          rm -rf ./sdk-output/v2
          java -jar openapi-generator-cli.jar generate -i ../idn/sailpoint-api.v2.yaml -g powershell -o sdk-output/v2 --global-property skipFormModel=false --config sdk-resources/v2-config.yaml

      - name: Build CC SDK
        id: buildCC
        if: steps.buildV2.outcome == 'success'
        run: |
          cd powershell-sdk
          rm -rf ./sdk-output/cc
          java -jar openapi-generator-cli.jar generate -i ../idn/sailpoint-api.cc.yaml -g powershell -o sdk-output/cc --global-property skipFormModel=false --config sdk-resources/cc-config.yaml

      - name: After SDK Generation
        id: buildSDK
        if: steps.buildCC.outcome == 'success'
        shell: pwsh
        run: |
          $DebugPreference="Continue"
          Import-Module -Name '.\sdk-output' -Verbose
      
      - name: After SDK Build
        if: steps.buildSDK.outcome == 'success'
        run: |
          cd powershell-sdk
          git config --unset-all http.https://github.com/.extraheader
          git config --local user.email "tyler.mairose@sailpoint.com"
          git config --local user.name "GitHub Action Bot"

          git add .
          git commit -m "Automated build '${{ github.event.head_commit.message }}' powershell sdk: ${{ github.run_id }}"

          git status

          git remote set-url origin https://${{secrets.API_SPEC_PAT}}@github.com/sailpoint-oss/powershell.git

          git remote -v